server:
  port: 8082

spring:
  datasource:
    clickhouse:
      jdbc-url: jdbc:clickhouse://127.0.0.1:18123/clklog
      username: default
      password: 123456
      driver-class-name: com.clickhouse.jdbc.ClickHouseDriver

init:
  log-db: clklog
  quartz-enabled: false
